#!/bin/bash
#PBS -j oe 
#PBS -l nodes=1:ppn=24
#PBS -q batch
#PBS -l walltime=240:60:00
cd $PBS_O_WORKDIR
NPROCS=`wc -l < $PBS_NODEFILE`
cat $PBS_NODEFILE > nodefile
#Run the parallel MPI executable a.out
date >> $HOME/run.txt
pwd >> $HOME/run.txt
echo This job has allocated $NPROCS $PBS_NODEFILE >> $HOME/run.txt
#export  VASP=/opt/VASP5.3.5/vasp.5.3/vasp
export  VASP=~/soft/vasp.5.4.4/bin/vasp_std
#export VASP=/opt/VASP5.3.5/vasp.5.3_nc/vasp
#export VASP=/opt/VASP5.3.5/vasp.5.3_wan/vasp
#export VASP=/opt/VASP5.3.5/soc-wan/vasp
NPROCS=`wc -l < $PBS_NODEFILE`
mpirun -np $NPROCS $VASP> output
